---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-storageclass
  resources:
    requests:
      storage: 20Gi