apiVersion: v1
kind: Service
metadata:
  name: sftp-service
  namespace: wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0d3d861e063eec242"  # Especifica el ID del grupo de seguridad
    service.beta.kubernetes.io/aws-load-balancer-name: "genaia-prod"

spec:
  selector:
    app: sftp
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: wordpress
  labels:
    environment: production
    app: sftp
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sftp
      environment: production
  template:
    metadata:
      labels:
        app: sftp
        environment: production
    spec:
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-pvc-wordpress
      containers:
      - name: sftp
        image: 105054799343.dkr.ecr.eu-south-2.amazonaws.com/sftp-stratio:prod-0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/www
          name: persistent-storage
