apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: wordpress # O elimina esta línea si es un ClusterRole a nivel de clúster
  name: rundeck-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "services", "deployments"] # Ajusta estos recursos según tus necesidades
  verbs: ["get", "list", "create", "update", "delete"] # Ajusta los verbos según tus necesidades
